[package]
name = "dicom_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
#chrono = "0.4.26"
dicom = "0.7.0"
walkdir = "2.5"
#dicom-pixeldata = { version = "0.2.0", features = ["ndarray"] }
#serde = { version = "1.0.183", features = ["derive"] }
#serde_json = "1.0.105"
