[package]
name = "dicom_reader"
version = "0.1.0"
edition = "2021"

[lib]
name = "dicom_reader"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.26"
dicom = "0.6.0"
dicom-pixeldata = { version = "0.2.0", features = ["ndarray"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
