[project]
name = "dicom_reader"
version = "0.1.0"
description = "Reader to load data from DICOM files into Apache Arrow"
authors = ["Marc Garcia <garcia.marc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]  # --> add in "osx-arm64" for MacOS

[tasks]
main = "DYLD_LIBRARY_PATH=target/debug python dicom_reader/__init__.py"   

##For MacOS change from LD_LIBRARY_PATH --> DYLD_LIBRARY_PATH 

[dependencies]
python = "3.11.4.*"
